In [1]:
import pandas as pd
import sqlite3
from pathlib import Path

In [2]:
csv_path = Path("../data/processed data/sales_cleaned_data.csv")

print("File exists:", csv_path.exists())
print("Full path:", csv_path.resolve())

File exists: True
Full path: C:\Users\yuvra\OneDrive\Desktop\DA projects\Amazon festival sales analysis\data\processed data\sales_cleaned_data.csv

In [3]:
#reading csv file
df = pd.read_csv(csv_path)

In [4]:
# Database connection
conn = sqlite3.connect("../sql/amazon_analytics.db")

# importing csv data to db
df.to_sql(
    name="amazon_sales",
    con=conn,
    if_exists="replace",
    index=False
)

print("CSV data successfully imported")

CSV data successfully imported

In [5]:
#checking connection is working or not
query = """
SELECT COUNT(*) AS total_rows
FROM amazon_sales;
"""

display(pd.read_sql_query(query, conn))

   total_rows
0      128943

In [6]:
query = """
SELECT *
FROM amazon_sales
LIMIT 1;
"""

display(pd.read_sql_query(query, conn))

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,asin,courier_status,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,b2b
0,171-7326790-9044369,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3614,JNE3614-KR-L,Kurta,L,B098133PV7,Shipped,1,INR,453.0,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317,IN,0

In [8]:
#Q-1 How many total records, unique orders, and total units ordered are present in the dataset?
query = """
    select 
    count(*) as total_record,
    count(DISTINCT order_id) as unique_record,
    sum(qty) as total_orders
    from Amazon_sales;
    
"""
result = pd.read_sql_query(query, conn)
display(result)

   total_record  unique_record  total_orders
0        128943         120352        116648

In [12]:
#Q3. Which product categories generate the highest sales and order volumes?
query = """
    select 
    category,
    sum(amount) as total_sales,
    count(order_id) as total_orders
    from Amazon_sales
    GROUP BY category
    ORDER BY total_sales desc;
    
"""
result = pd.read_sql_query(query, conn)
display(result)

        category  total_sales  total_orders
0            Set  41295773.17         50272
1          Kurta  23341914.20         49864
2  Western Dress  11728629.69         15495
3            Top   5643606.80         10621
4   Ethnic Dress    833163.66          1158
5         Blouse    487590.68           926
6         Bottom    163637.98           440
7          Saree    129770.26           164
8        Dupatta       915.00             3